# Generated by Django 4.0.3 on 2022-04-05 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dj_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
